name: Chapmandu
favicon: null
layout_spectrum: 0.8647091733291745
typography_spectrum: 0.6365125798620284
title: "Adam's Digital Cesspool"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#3b5346'
    - '#61cfea'
    - '#d03f21'
  brandStrength: 0.42532711708918214
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 0.8748132709879428
purpose: []
