name: Chapmandu
favicon: null
layout_spectrum: 0.8647091733291745
typography_spectrum: 0.6365125798620284
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.42532711708918214
  lightness: 0.7575818605255336
  saturation: 0.07453501760028303
  rhythmicContrast: 0.8748132709879428
purpose: []
